<a href="https://colab.research.google.com/github/MomooDiane/Data-Extraction-Assignment/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 3 - Question 1

Extraction of the tables from the database

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("hopital.db")
cursor = conn.cursor()
create_tables_sql = """
CREATE TABLE Employees (
    medicare_card_num VARCHAR(255) PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    date_of_birth DATE NOT NULL,
    phone_number VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    province VARCHAR(255),
    postal_code VARCHAR(10),
    citizenship VARCHAR(255),
    email_address VARCHAR(255) UNIQUE
);

CREATE TABLE Facilities (
    name VARCHAR(255) NOT NULL,
    web_address VARCHAR(255) NOT NULL,
    capacity INT,
    type VARCHAR(255),
    address VARCHAR(255),
    city VARCHAR(255),
    province VARCHAR(255),
    postal_code VARCHAR(10),
    phone_number VARCHAR(20),
    CONSTRAINT PK_Facilities PRIMARY KEY (name, web_address)
);

CREATE TABLE Infections (
    type VARCHAR(255) PRIMARY KEY
);

CREATE TABLE Vaccines (
    type VARCHAR(255) PRIMARY KEY
);

CREATE TABLE Infected (
    medicare_card_num VARCHAR(12),
    type VARCHAR(255),
    infection_count INT,
    date DATE,
    PRIMARY KEY (medicare_card_num, type, infection_count),
    FOREIGN KEY (medicare_card_num) REFERENCES Employees(medicare_card_num),
    FOREIGN KEY (type) REFERENCES Infections(type)
);

CREATE TABLE Has_Received (
    medicare_card_num VARCHAR(12),
    vaccine_type VARCHAR(255),
    facility_name VARCHAR(255),
    web_address VARCHAR(255),
    date DATE,
    dose_num INT,
    PRIMARY KEY (facility_name, web_address, medicare_card_num, vaccine_type, dose_num),
    FOREIGN KEY (vaccine_type) REFERENCES Vaccines(type),
    FOREIGN KEY (facility_name, web_address) REFERENCES Facilities(name, web_address),
    FOREIGN KEY (medicare_card_num) REFERENCES Employees(medicare_card_num)
);

CREATE TABLE Administers (
    facility_name VARCHAR(255),
    web_address VARCHAR(255),
    vaccine_type VARCHAR(255),
    PRIMARY KEY (facility_name, web_address, vaccine_type),
    FOREIGN KEY (facility_name, web_address) REFERENCES Facilities(name, web_address),
    FOREIGN KEY (vaccine_type) REFERENCES Vaccines(type)
);

CREATE TABLE Managed (
    facility_name VARCHAR(255),
    web_address VARCHAR(255),
    medicare_card_num VARCHAR(12),
    start_date DATE,
    end_date DATE,
    PRIMARY KEY (medicare_card_num, start_date),
    FOREIGN KEY (facility_name, web_address) REFERENCES Facilities(name, web_address),
    FOREIGN KEY (medicare_card_num) REFERENCES Employees(medicare_card_num)
);


CREATE TABLE Worked (
    facility_name VARCHAR(255),
    web_address VARCHAR(255),
    medicare_card_num VARCHAR(12),
    start_date DATE,
    end_date DATE,
    role VARCHAR(255),
    PRIMARY KEY (medicare_card_num, start_date),
    FOREIGN KEY (facility_name, web_address) REFERENCES Facilities(name, web_address),
    FOREIGN KEY (medicare_card_num) REFERENCES Employees(medicare_card_num)
 );

"""

In [ ]:
cursor.executescript(create_tables_sql)
conn.commit()

In [ ]:
insert_data_sql = """

INSERT INTO Employees(medicare_card_num, first_name, last_name, date_of_birth, phone_number, address, city, province, postal_code, citizenship, email_address)
VALUES
('12345678', 'Alice', 'Roberts', '1995-05-15', '+11234567890', '111 1st street', 'Montreal', 'Quebec', 'H2X1E6', 'Canada', 'AliceRoberts@mail.com'),
('23456789', 'Bob', 'Johnson', '1990-07-21', '+11234567891', '112 2nd street', 'Toronto', 'Ontario', 'M5H2N2', 'Canada', 'BobJohnson@mail.com'),
('34567890', 'Carol', 'Williams', '1991-09-28', '+11234567892', '113 3rd street', 'Vancouver', 'British Columbia', 'V6E1A3', 'Canada', 'CarolWilliams@mail.com'),
('45122911', 'Dave', 'Jones', '1995-03-12', '+11234567893', '114 4th street', 'Ottawa', 'Ontario', 'K1N7A2', 'Canada', 'DaveJones@mail.com'),
('56789012', 'Eve', 'Brown', '1993-11-02', '+11234567894', '115 5th street', 'Montreal', 'Quebec', 'H2Y1M2', 'Canada', 'EveBrown@mail.com'),
('67890123', 'Frank', 'Smith', '1998-02-28', '+11234567895', '116 6th street', 'Toronto', 'Ontario', 'M5J1C3', 'Canada', 'FrankSmith@mail.com'),
('78901234', 'Grace', 'Taylor', '1992-12-18', '+11234567896', '117 7th street', 'Vancouver', 'British Columbia', 'V6C3A8', 'Canada', 'GraceTaylor@mail.com'),
('89012345', 'Harry', 'Adams', '1999-01-03', '+11234567897', '118 8th street', 'Ottawa', 'Ontario', 'K1P5M7', 'Canada', 'HarryAdams@mail.com'),
('90123456', 'Ivy', 'Martin', '1994-06-20', '+11234567898', '119 9th street', 'Montreal', 'Quebec', 'H2Z1H5', 'Canada', 'IvyMartin@mail.com'),
('01234567', 'Jack', 'Lee', '1997-08-11', '+11234567899', '120 10th street', 'Toronto', 'Ontario', 'M5G1R7', 'Canada', 'JackLee@mail.com'),
('12345670', 'Kathy', 'King', '1996-04-09', '+11234567800', '121 11th street', 'Vancouver', 'British Columbia', 'V6E2P4', 'Canada', 'KathyKing@mail.com'),
('23456780', 'Larry', 'Baker', '1991-10-26', '+11234567901', '122 12th street', 'Ottawa', 'Ontario', 'K2P2M2', 'Canada', 'LarryBaker@mail.com'),
('34363499', 'Mona', 'Turner', '1999-02-14', '+11234567902', '123 13th street', 'Montreal', 'Quebec', 'H2X2W2', 'Canada', 'MonaTurner@mail.com'),
('45678901', 'Nate', 'Hill', '1992-05-08', '+11234567903', '124 14th street', 'Toronto', 'Ontario', 'M4S1Y5', 'Canada', 'NateHill@mail.com'),
('56789111', 'Olivia', 'James', '1993-12-17', '+11234567904', '125 15th street', 'Vancouver', 'British Columbia', 'V6H3L6', 'Canada', 'OliviaJames@mail.com'),
('98765432', 'Peter', 'Clark', '1991-06-08', '+11234567890', '126 6th street', 'Ottawa', 'Ontario', 'K1N7A2', 'Canada', 'PeterClark@mail.com'),
('87654321', 'Queen', 'Scott', '1993-09-12', '+11234567891', '127 5th street', 'Montreal', 'Quebec', 'H2Y1M2', 'Canada', 'QueenScott@mail.com'),
('76543210', 'Ron', 'Stewart', '1992-01-21', '+11234567892', '128 8th street', 'Toronto', 'Ontario', 'M5J1C3', 'Canada', 'RonStewart@mail.com'),
('65432109', 'Sarah', 'Hall', '1996-04-16', '+11234567893', '129 9th street', 'Vancouver', 'British Columbia', 'V6C3A8', 'Canada', 'SarahHall@mail.com'),
('54321098', 'Tom', 'Perez', '1999-11-01', '+11234567894', '130 20th street', 'Ottawa', 'Ontario', 'K1P5M7', 'Canada', 'TomPerez@mail.com'),
('76543211', 'Ursula', 'Nelson', '1997-02-05', '+11234567895', '130 1st street', 'Montreal', 'Quebec', 'H2X1E6', 'Canada', 'UrsulaNelson@mail.com'),
('65432112', 'Vic', 'Phillips', '1994-11-12', '+11234567896', '131 2nd street', 'Toronto', 'Ontario', 'M5H2N2', 'Canada', 'VicPhillips@mail.com'),
('54321093', 'Wanda', 'Rodriguez', '1990-09-20', '+11234567897', '132 3rd street', 'Vancouver', 'British Columbia', 'V6E1A3', 'Canada', 'WandaRodriguez@mail.com'),
('43210987', 'Xander', 'Harris', '1995-07-08', '+11234567898', '133 4th street', 'Ottawa', 'Ontario', 'K1N7A2', 'Canada', 'XanderHarris@mail.com'),
('32109876', 'John', 'Doe', '1993-04-18', '+11234567899', '134 5th street', 'Montreal', 'Quebec', 'H2Y1M2', 'Canada', 'JohnDoe@mail.com'),
('21098765', 'Momo', 'Diane', '1998-12-01', '+11234567800', '135 6th street', 'Toronto', 'Ontario', 'M5J1C3', 'Canada', 'MomoDiane@mail.com'),
('10987654', 'Philip', 'Tomas', '1992-08-26', '+11234567801', '136 7th street', 'Vancouver', 'British Columbia', 'V6C3A8', 'Canada', 'PhilipTomas@mail.com');


INSERT INTO Facilities (name, web_address, capacity, type, address, city, province, postal_code, phone_number)
VALUES
('hospital1', 'hospital1.com', 7, 'hospital', '1st street', 'Montreal', 'Quebec', 'H2X1E6', '5141234567'),
('hospital2', 'hospital2.com', 8, 'hospital', '2nd street', 'Toronto', 'Ontario', 'M5V2H1', '4161234567'),
('clinic1', 'clinic1.com', 5, 'clinic', '3rd street', 'Toronto', 'Ontario', 'M5V2H3', '6041234567'),
('special1', 'special1.com', 5, 'special installment', '8th street', 'Ottawa', 'Ontario', 'K1N6N5', '6131234567'),
('CLSC1', 'CLSC1.com', 10, 'CLSC', '5th street', 'Montreal', 'Quebec', 'H2Y1C6', '5141234567'),
('hospital3', 'hospital3.com', 7, 'hospital', '6th street', 'Toronto', 'Ontario', 'M4T1T3', '4161234567'),
('clinic2', 'clinic2.com', 8, 'clinic', '7th street', 'Vancouver', 'British Columbia', 'V5Y1V4', '6041234567'),
('special2', 'special2.com', 6, 'special installment', '4th street', 'Vancouver', 'British Columbia', 'V6Z2C5', '6131234567'),
('hospital4', 'hospital4.com', 6, 'hospital', '9th street', 'Montreal', 'Quebec', 'H2Z1G1', '5141234567'),
('clinic3', 'clinic3.com', 9, 'clinic', '10th street', 'Vancouver', 'British Columbia', 'V6B2S9', '6041234567'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', 9, 'hospital', '5415 Assomption Blvd', 'Montreal', 'Quebec', 'H1T2M4', '8041336367');


INSERT INTO Infections (type)
VALUES
('COVID-19'),
('SARS-Cov-2 Variant'),
('SARS-Cov-3 Variant'),
('Alpha Variant'),
('Beta Variant'),
('Gamma Variant'),
('Delta Variant'),
('Lambda Variant'),
('Omicron Variant'),
('Epsilon Variant');



INSERT INTO Vaccines (type)
VALUES
("Pfizer"),
("Moderna"),
("AstraZeneca"),
("Johnson & Johnson"),
("Novavax"),
("Sinovac"),
("Sinopharm"),
("Bharat Biotech"),
("Covovax"),
("Covishield");



INSERT INTO Infected(medicare_card_num, type, infection_count, date)
VALUES
('12345678', 'COVID-19', 1, '2021-01-01'),
('12345678', 'SARS-Cov-2 Variant', 2, '2022-02-02'),
('23456789', 'COVID-19', 1, '2020-03-03'),
('23456789', 'Alpha Variant', 1, '2020-05-05'),
('34567890', 'COVID-19', 1, '2021-04-04'),
('34567890', 'Beta Variant', 1, '2021-06-06'),
('45122911', 'COVID-19', 2, '2021-02-02'),
('45122911', 'Gamma Variant', 1, '2020-07-07'),
('56789012', 'COVID-19', 1, '2021-03-03'),
('56789012', 'Delta Variant', 2, '2021-08-08'),
('67890123', 'COVID-19', 1, '2020-04-04'),
('67890123', 'Lambda Variant', 1, '2020-09-09'),
('78901234', 'COVID-19', 2, '2022-02-02'),
('78901234', 'Omicron Variant', 1, '2021-11-11'),
('89012345', 'COVID-19', 1, '2020-01-01'),
('89012345', 'Epsilon Variant', 1, '2020-10-10'),
('90123456', 'COVID-19', 2, '2022-05-05'),
('90123456', 'SARS-Cov-3 Variant', 1, '2021-12-12'),
('01234567', 'COVID-19', 1, '2020-06-06'),
('01234567', 'Beta Variant', 1, '2020-11-11'),
('76543211', 'COVID-19', 1, '2021-01-01'),
('65432112', 'COVID-19', 1, '2021-02-01'),
('54321093', 'COVID-19', 1, '2021-03-01'),
('76543211', 'Alpha Variant', 2, '2020-05-05'),
('65432112', 'Alpha Variant', 2, '2020-06-05'),
('54321093', 'Alpha Variant', 2, '2020-07-05'),
('76543211', 'Gamma Variant', 3, '2020-07-07'),
('65432112', 'Gamma Variant', 3, '2020-08-07'),
('54321093', 'Gamma Variant', 3, '2020-09-07');


INSERT INTO Has_Received(medicare_card_num, vaccine_type, facility_name, web_address, date, dose_num)
VALUES
('12345678', 'Pfizer', 'hospital1', 'hospital1.com', '2022-01-10', 1),
('23456789', 'AstraZeneca', 'hospital2', 'hospital2.com', '2021-07-05', 1),
('23456789', 'Johnson & Johnson', 'clinic1', 'clinic1.com', '2022-02-01', 2),
('34567890', 'Pfizer', 'hospital1', 'hospital1.com', '2021-12-24', 1),
('45122911', 'Bharat Biotech', 'clinic2', 'clinic2.com', '2021-06-15', 1),
('45122911', 'Novavax', 'special1', 'special1.com', '2022-01-02', 2),
('56789012', 'Covishield', 'hospital4', 'hospital4.com', '2021-09-30', 1),
('67890123', 'Sinopharm', 'clinic3', 'clinic3.com', '2022-02-10', 1),
('78901234', 'Pfizer', 'hospital2', 'hospital2.com', '2021-07-02', 1),
('78901234', 'Covishield', 'CLSC1', 'CLSC1.com', '2022-01-15', 2),
('90123456', 'Johnson & Johnson', 'clinic1', 'clinic1.com', '2020-12-03', 1),
('01234567', 'AstraZeneca', 'hospital2', 'hospital2.com', '2022-01-08', 1),
('12345670', 'Sinovac', 'hospital4', 'hospital4.com', '2022-02-08', 1),
('23456780', 'Pfizer', 'special1', 'special1.com', '2021-10-11', 1),
('34363499', 'AstraZeneca', 'special2', 'special2.com', '2021-11-23', 1),
('45678901', 'Johnson & Johnson', 'clinic2', 'clinic2.com', '2021-12-05', 1),
('56789111', 'Covovax', 'special2', 'special2.com', '2022-01-09', 1),
('98765432', 'Bharat Biotech', 'clinic2', 'clinic2.com', '2021-09-20', 1),
('87654321', 'Moderna', 'hospital1', 'hospital1.com', '2021-12-01', 1),
('87654321', 'AstraZeneca', 'hospital2', 'hospital2.com', '2021-09-03', 2),
('65432109', 'Sinopharm', 'clinic3', 'clinic3.com', '2021-09-18', 1),
('65432109', 'Covishield', 'CLSC1', 'CLSC1.com', '2022-02-12', 2);


INSERT INTO Administers (facility_name, web_address, vaccine_type)
VALUES
('hospital1', 'hospital1.com', 'Pfizer'),
('hospital1', 'hospital1.com', 'Moderna'),
('hospital2', 'hospital2.com', 'AstraZeneca'),
('clinic1', 'clinic1.com', 'Johnson & Johnson'),
('special1', 'special1.com', 'Novavax'),
('CLSC1', 'CLSC1.com', 'Sinovac'),
('hospital3', 'hospital3.com', 'Sinopharm'),
('clinic2', 'clinic2.com', 'Bharat Biotech'),
('special2', 'special2.com', 'Covovax'),
('hospital4', 'hospital4.com', 'Covishield'),
('hospital1', 'hospital1.com', 'AstraZeneca'),
('hospital2', 'hospital2.com', 'Pfizer'),
('clinic1', 'clinic1.com', 'Moderna'),
('special1', 'special1.com', 'Pfizer'),
('CLSC1', 'CLSC1.com', 'Covishield'),
('hospital3', 'hospital3.com', 'Covovax'),
('clinic2', 'clinic2.com', 'Johnson & Johnson'),
('special2', 'special2.com', 'AstraZeneca'),
('hospital4', 'hospital4.com', 'Sinovac'),
('clinic3', 'clinic3.com', 'Sinopharm');



INSERT INTO Managed(facility_name, web_address, medicare_card_num, start_date, end_date)
VALUES
('hospital1', 'hospital1.com', '12345678', '2022-01-01', '2022-01-31'),
('hospital2', 'hospital2.com', '34567890', '2022-02-01', '2022-02-28'),
('clinic1', 'clinic1.com', '56789012', '2022-03-01', '2022-03-31'),
('special1', 'special1.com', '78901234', '2022-04-01', '2022-04-30'),
('CLSC1', 'CLSC1.com', '90123456', '2022-05-01', '2022-05-31'),
('hospital3', 'hospital3.com', '12345678', '2022-06-01', NULL),
('clinic2', 'clinic2.com', '34567890', '2022-07-01', NULL),
('special2', 'special2.com', '56789012', '2022-08-01', NULL),
('hospital4', 'hospital4.com', '78901234', '2022-09-01', NULL),
('clinic3', 'clinic3.com', '90123456', '2022-10-01', '2022-10-31'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '10987654', '2022-07-01', NULL);




INSERT INTO Worked(facility_name, web_address, medicare_card_num, start_date, end_date, role)
VALUES
('hospital1', 'hospital1.com', '12345678', '2022-01-01', '2022-01-31', 'Manager'),
('hospital1', 'hospital1.com', '23456789', '2022-01-01', NULL, 'Doctor'),
('hospital2', 'hospital2.com', '34567890', '2022-02-01', '2022-02-28', 'Manager'),
('hospital2', 'hospital2.com', '45122911', '2022-02-01', NULL, 'Doctor'),
('clinic1', 'clinic1.com', '56789012', '2022-03-01', '2022-03-31', 'Manager'),
('clinic1', 'clinic1.com', '67890123', '2022-03-01', NULL, 'Doctor'),
('special1', 'special1.com', '78901234', '2022-04-01', '2022-04-30', 'Manager'),
('special1', 'special1.com', '89012345', '2022-04-01', NULL, 'Doctor'),
('CLSC1', 'CLSC1.com', '90123456', '2022-05-01', '2022-05-31', 'Manager'),
('CLSC1', 'CLSC1.com', '01234567', '2022-05-01', '2022-05-31', 'Doctor'),
('hospital3', 'hospital3.com', '12345678', '2022-06-01', NULL, 'Manager'),
('hospital3', 'hospital3.com', '23456789', '2022-06-01', '2022-06-30', 'Doctor'),
('clinic2', 'clinic2.com', '34567890', '2022-07-01', NULL, 'Manager'),
('clinic2', 'clinic2.com', '45122911', '2022-07-01', '2022-07-31', 'Doctor'),
('special2', 'special2.com', '56789012', '2022-08-01', NULL, 'Manager'),
('special2', 'special2.com', '67890123', '2022-08-01', NULL, 'Doctor'),
('hospital4', 'hospital4.com', '78901234', '2022-09-01', NULL, 'Manager'),
('hospital4', 'hospital4.com', '89012345', '2022-09-01', NULL, 'Doctor'),
('clinic3', 'clinic3.com', '90123456', '2022-10-01', '2022-10-31', 'Manager'),
('clinic3', 'clinic3.com', '01234567', '2020-10-01', '2020-10-30', 'Doctor'),
('hospital4', 'hospital4.com', '90123456', '2021-10-01', '2021-10-30', 'Doctor'),
('special2', 'special2.com', '45122911', '2022-10-01', NULL, 'Doctor'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '76543211', '2022-07-01', NULL, 'Doctor'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '65432112', '2022-07-01', NULL, 'Nurse'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '54321093', '2022-07-01', NULL, 'Nurse'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '43210987', '2022-07-01', '2022-07-31', 'Doctor'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '32109876', '2022-07-01', NULL, 'Nurse'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '21098765', '2022-07-01', '2022-07-31', 'Nurse'),
('Hospital Maisonneuve Rosemont', 'Hospital-Maisonneuve-Rosemont.com', '10987654', '2022-07-01', NULL, 'Manager');

"""

In [ ]:
cursor.executescript(insert_data_sql)

In [ ]:
conn.commit()

Test to display Employees Table

In [ ]:
COMMAND = "SELECT * FROM Employees"
employees_data = pd.read_sql_query(COMMAND, conn)

In [ ]:
employees_data

,medicare_card_num,first_name,last_name,date_of_birth,phone_number,address,city,province,postal_code,citizenship,email_address
0,12345678,Alice,Roberts,1995-05-15,+11234567890,111 1st street,Montreal,Quebec,H2X1E6,Canada,AliceRoberts@mail.com
1,23456789,Bob,Johnson,1990-07-21,+11234567891,112 2nd street,Toronto,Ontario,M5H2N2,Canada,BobJohnson@mail.com
2,34567890,Carol,Williams,1991-09-28,+11234567892,113 3rd street,Vancouver,British Columbia,V6E1A3,Canada,CarolWilliams@mail.com
3,45122911,Dave,Jones,1995-03-12,+11234567893,114 4th street,Ottawa,Ontario,K1N7A2,Canada,DaveJones@mail.com
4,56789012,Eve,Brown,1993-11-02,+11234567894,115 5th street,Montreal,Quebec,H2Y1M2,Canada,EveBrown@mail.com
5,67890123,Frank,Smith,1998-02-28,+11234567895,116 6th street,Toronto,Ontario,M5J1C3,Canada,FrankSmith@mail.com
6,78901234,Grace,Taylor,1992-12-18,+11234567896,117 7th street,Vancouver,British Columbia,V6C3A8,Canada,GraceTaylor@mail.com
7,89012345,Harry,Adams,1999-01-03,+11234567897,118 8th street,Ottawa,Ontario,K1P5M7,Canada,HarryAdams@mail.com
8,90123456,Ivy,Martin,1994-06-20,+11234567898,119 9th street,Montreal,Quebec,H2Z1H5,Canada,IvyMartin@mail.com
9,01234567,Jack,Lee,1997-08-11,+11234567899,120 10th street,Toronto,Ontario,M5G1R7,Canada,JackLee@mail.com
10,12345670,Kathy,King,1996-04-09,+11234567800,121 11th street,Vancouver,British Columbia,V6E2P4,Canada,KathyKing@mail.com
11,23456780,Larry,Baker,1991-10-26,+11234567901,122 12th street,Ottawa,Ontario,K2P2M2,Canada,LarryBaker@mail.com
12,34363499,Mona,Turner,1999-02-14,+11234567902,123 13th street,Montreal,Quebec,H2X2W2,Canada,MonaTurner@mail.com
13,45678901,Nate,Hill,1992-05-08,+11234567903,124 14th street,Toronto,Ontario,M4S1Y5,Canada,NateHill@mail.com
14,56789111,Olivia,James,1993-12-17,+11234567904,125 15th street,Vancouver,British Columbia,V6H3L6,Canada,OliviaJames@mail.com
15,98765432,Peter,Clark,1991-06-08,+11234567890,126 6th street,Ottawa,Ontario,K1N7A2,Canada,PeterClark@mail.com
16,87654321,Queen,Scott,1993-09-12,+11234567891,127 5th street,Montreal,Quebec,H2Y1M2,Canada,QueenScott@mail.com
17,76543210,Ron,Stewart,1992-01-21,+11234567892,128 8th street,Toronto,Ontario,M5J1C3,Canada,RonStewart@mail.com
18,65432109,Sarah,Hall,1996-04-16,+11234567893,129 9th street,Vancouver,British Columbia,V6C3A8,Canada,SarahHall@mail.com
19,54321098,Tom,Perez,1999-11-01,+11234567894,130 20th street,Ottawa,Ontario,K1P5M7,Canada,TomPerez@mail.com
20,76543211,Ursula,Nelson,1997-02-05,+11234567895,130 1st street,Montreal,Quebec,H2X1E6,Canada,UrsulaNelson@mail.com
21,65432112,Vic,Phillips,1994-11-12,+11234567896,131 2nd street,Toronto,Ontario,M5H2N2,Canada,VicPhillips@mail.com
22,54321093,Wanda,Rodriguez,1990-09-20,+11234567897,132 3rd street,Vancouver,British Columbia,V6E1A3,Canada,WandaRodriguez@mail.com
23,43210987,Xander,Harris,1995-07-08,+11234567898,133 4th street,Ottawa,Ontario,K1N7A2,Canada,XanderHarris@mail.com
24,32109876,John,Doe,1993-04-18,+11234567899,134 5th street,Montreal,Quebec,H2Y1M2,Canada,JohnDoe@mail.com
25,21098765,Momo,Diane,1998-12-01,+11234567800,135 6th street,Toronto,Ontario,M5J1C3,Canada,MomoDiane@mail.com
26,10987654,Philip,Tomas,1992-08-26,+11234567801,136 7th street,Vancouver,British Columbia,V6C3A8,Canada,PhilipTomas@mail.com

Conversion of Employees table into a DataFrame

In [ ]:
employees_df = employees_data
print(employees_df)

   medicare_card_num first_name  last_name date_of_birth  phone_number  \
0           12345678      Alice    Roberts    1995-05-15  +11234567890
1           23456789        Bob    Johnson    1990-07-21  +11234567891
2           34567890      Carol   Williams    1991-09-28  +11234567892
3           45122911       Dave      Jones    1995-03-12  +11234567893
4           56789012        Eve      Brown    1993-11-02  +11234567894
5           67890123      Frank      Smith    1998-02-28  +11234567895
6           78901234      Grace     Taylor    1992-12-18  +11234567896
7           89012345      Harry      Adams    1999-01-03  +11234567897
8           90123456        Ivy     Martin    1994-06-20  +11234567898
9           01234567       Jack        Lee    1997-08-11  +11234567899
10          12345670      Kathy       King    1996-04-09  +11234567800
11          23456780      Larry      Baker    1991-10-26  +11234567901
12          34363499       Mona     Turner    1999-02-14  +11234567902
13          45678901       Nate       Hill    1992-05-08  +11234567903
14          56789111     Olivia      James    1993-12-17  +11234567904
15          98765432      Peter      Clark    1991-06-08  +11234567890
16          87654321      Queen      Scott    1993-09-12  +11234567891
17          76543210        Ron    Stewart    1992-01-21  +11234567892
18          65432109      Sarah       Hall    1996-04-16  +11234567893
19          54321098        Tom      Perez    1999-11-01  +11234567894
20          76543211     Ursula     Nelson    1997-02-05  +11234567895
21          65432112        Vic   Phillips    1994-11-12  +11234567896
22          54321093      Wanda  Rodriguez    1990-09-20  +11234567897
23          43210987     Xander     Harris    1995-07-08  +11234567898
24          32109876       John        Doe    1993-04-18  +11234567899
25          21098765       Momo      Diane    1998-12-01  +11234567800
26          10987654     Philip      Tomas    1992-08-26  +11234567801

            address       city          province postal_code citizenship  \
0    111 1st street   Montreal            Quebec      H2X1E6      Canada
1    112 2nd street    Toronto           Ontario      M5H2N2      Canada
2    113 3rd street  Vancouver  British Columbia      V6E1A3      Canada
3    114 4th street     Ottawa           Ontario      K1N7A2      Canada
4    115 5th street   Montreal            Quebec      H2Y1M2      Canada
5    116 6th street    Toronto           Ontario      M5J1C3      Canada
6    117 7th street  Vancouver  British Columbia      V6C3A8      Canada
7    118 8th street     Ottawa           Ontario      K1P5M7      Canada
8    119 9th street   Montreal            Quebec      H2Z1H5      Canada
9   120 10th street    Toronto           Ontario      M5G1R7      Canada
10  121 11th street  Vancouver  British Columbia      V6E2P4      Canada
11  122 12th street     Ottawa           Ontario      K2P2M2      Canada
12  123 13th street   Montreal            Quebec      H2X2W2      Canada
13  124 14th street    Toronto           Ontario      M4S1Y5      Canada
14  125 15th street  Vancouver  British Columbia      V6H3L6      Canada
15   126 6th street     Ottawa           Ontario      K1N7A2      Canada
16   127 5th street   Montreal            Quebec      H2Y1M2      Canada
17   128 8th street    Toronto           Ontario      M5J1C3      Canada
18   129 9th street  Vancouver  British Columbia      V6C3A8      Canada
19  130 20th street     Ottawa           Ontario      K1P5M7      Canada
20   130 1st street   Montreal            Quebec      H2X1E6      Canada
21   131 2nd street    Toronto           Ontario      M5H2N2      Canada
22   132 3rd street  Vancouver  British Columbia      V6E1A3      Canada
23   133 4th street     Ottawa           Ontario      K1N7A2      Canada
24   134 5th street   Montreal            Quebec      H2Y1M2      Canada
25   135 6th street    Toronto           Ontario      M5J1C3      Canada
26   136 7th street  Vancouver  British Columbia      V6C3A8      Canada

              email_address
0     AliceRoberts@mail.com
1       BobJohnson@mail.com
2    CarolWilliams@mail.com
3        DaveJones@mail.com
4         EveBrown@mail.com
5       FrankSmith@mail.com
6      GraceTaylor@mail.com
7       HarryAdams@mail.com
8        IvyMartin@mail.com
9          JackLee@mail.com
10       KathyKing@mail.com
11      LarryBaker@mail.com
12      MonaTurner@mail.com
13        NateHill@mail.com
14     OliviaJames@mail.com
15      PeterClark@mail.com
16      QueenScott@mail.com
17      RonStewart@mail.com
18       SarahHall@mail.com
19        TomPerez@mail.com
20    UrsulaNelson@mail.com
21     VicPhillips@mail.com
22  WandaRodriguez@mail.com
23    XanderHarris@mail.com
24         JohnDoe@mail.com
25       MomoDiane@mail.com
26     PhilipTomas@mail.com

In [ ]:
COMMAND = "SELECT * FROM Facilities"
facilities_data = pd.read_sql_query(COMMAND, conn)
facilities_data

,name,web_address,capacity,type,address,city,province,postal_code,phone_number
0,hospital1,hospital1.com,7,hospital,1st street,Montreal,Quebec,H2X1E6,5141234567
1,hospital2,hospital2.com,8,hospital,2nd street,Toronto,Ontario,M5V2H1,4161234567
2,clinic1,clinic1.com,5,clinic,3rd street,Toronto,Ontario,M5V2H3,6041234567
3,special1,special1.com,5,special installment,8th street,Ottawa,Ontario,K1N6N5,6131234567
4,CLSC1,CLSC1.com,10,CLSC,5th street,Montreal,Quebec,H2Y1C6,5141234567
5,hospital3,hospital3.com,7,hospital,6th street,Toronto,Ontario,M4T1T3,4161234567
6,clinic2,clinic2.com,8,clinic,7th street,Vancouver,British Columbia,V5Y1V4,6041234567
7,special2,special2.com,6,special installment,4th street,Vancouver,British Columbia,V6Z2C5,6131234567
8,hospital4,hospital4.com,6,hospital,9th street,Montreal,Quebec,H2Z1G1,5141234567
9,clinic3,clinic3.com,9,clinic,10th street,Vancouver,British Columbia,V6B2S9,6041234567
10,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,9,hospital,5415 Assomption Blvd,Montreal,Quebec,H1T2M4,8041336367

Conversion of Facilities table into a DataFrame

In [ ]:
facilities_df = facilities_data
print(facilities_df)

                             name                        web_address  \
0                       hospital1                      hospital1.com
1                       hospital2                      hospital2.com
2                         clinic1                        clinic1.com
3                        special1                       special1.com
4                           CLSC1                          CLSC1.com
5                       hospital3                      hospital3.com
6                         clinic2                        clinic2.com
7                        special2                       special2.com
8                       hospital4                      hospital4.com
9                         clinic3                        clinic3.com
10  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com

    capacity                 type               address       city  \
0          7             hospital            1st street   Montreal
1          8             hospital            2nd street    Toronto
2          5               clinic            3rd street    Toronto
3          5  special installment            8th street     Ottawa
4         10                 CLSC            5th street   Montreal
5          7             hospital            6th street    Toronto
6          8               clinic            7th street  Vancouver
7          6  special installment            4th street  Vancouver
8          6             hospital            9th street   Montreal
9          9               clinic           10th street  Vancouver
10         9             hospital  5415 Assomption Blvd   Montreal

            province postal_code phone_number
0             Quebec      H2X1E6   5141234567
1            Ontario      M5V2H1   4161234567
2            Ontario      M5V2H3   6041234567
3            Ontario      K1N6N5   6131234567
4             Quebec      H2Y1C6   5141234567
5            Ontario      M4T1T3   4161234567
6   British Columbia      V5Y1V4   6041234567
7   British Columbia      V6Z2C5   6131234567
8             Quebec      H2Z1G1   5141234567
9   British Columbia      V6B2S9   6041234567
10            Quebec      H1T2M4   8041336367

In [ ]:
COMMAND = "SELECT * FROM Infections "
infections_data = pd.read_sql_query(COMMAND, conn)
infections_data

                 type
0            COVID-19
1  SARS-Cov-2 Variant
2  SARS-Cov-3 Variant
3       Alpha Variant
4        Beta Variant
5       Gamma Variant
6       Delta Variant
7      Lambda Variant
8     Omicron Variant
9     Epsilon Variant

Conversion of Infections table into a DataFrame

In [ ]:
infections_df = infections_data
print(infections_df)

                 type
0            COVID-19
1  SARS-Cov-2 Variant
2  SARS-Cov-3 Variant
3       Alpha Variant
4        Beta Variant
5       Gamma Variant
6       Delta Variant
7      Lambda Variant
8     Omicron Variant
9     Epsilon Variant

In [ ]:
COMMAND = "SELECT * FROM Vaccines"
vaccines_data = pd.read_sql_query(COMMAND, conn)
vaccines_data

                type
0             Pfizer
1            Moderna
2        AstraZeneca
3  Johnson & Johnson
4            Novavax
5            Sinovac
6          Sinopharm
7     Bharat Biotech
8            Covovax
9         Covishield

Conversion of Vaccines table into a DataFrame

In [ ]:
vaccines_df = vaccines_data
print(vaccines_df)

                type
0             Pfizer
1            Moderna
2        AstraZeneca
3  Johnson & Johnson
4            Novavax
5            Sinovac
6          Sinopharm
7     Bharat Biotech
8            Covovax
9         Covishield

In [ ]:
COMMAND = "SELECT * FROM Infected"
infected_data = pd.read_sql_query(COMMAND, conn)
infected_data

   medicare_card_num                type  infection_count        date
0           12345678            COVID-19                1  2021-01-01
1           12345678  SARS-Cov-2 Variant                2  2022-02-02
2           23456789            COVID-19                1  2020-03-03
3           23456789       Alpha Variant                1  2020-05-05
4           34567890            COVID-19                1  2021-04-04
5           34567890        Beta Variant                1  2021-06-06
6           45122911            COVID-19                2  2021-02-02
7           45122911       Gamma Variant                1  2020-07-07
8           56789012            COVID-19                1  2021-03-03
9           56789012       Delta Variant                2  2021-08-08
10          67890123            COVID-19                1  2020-04-04
11          67890123      Lambda Variant                1  2020-09-09
12          78901234            COVID-19                2  2022-02-02
13          78901234     Omicron Variant                1  2021-11-11
14          89012345            COVID-19                1  2020-01-01
15          89012345     Epsilon Variant                1  2020-10-10
16          90123456            COVID-19                2  2022-05-05
17          90123456  SARS-Cov-3 Variant                1  2021-12-12
18          01234567            COVID-19                1  2020-06-06
19          01234567        Beta Variant                1  2020-11-11
20          76543211            COVID-19                1  2021-01-01
21          65432112            COVID-19                1  2021-02-01
22          54321093            COVID-19                1  2021-03-01
23          76543211       Alpha Variant                2  2020-05-05
24          65432112       Alpha Variant                2  2020-06-05
25          54321093       Alpha Variant                2  2020-07-05
26          76543211       Gamma Variant                3  2020-07-07
27          65432112       Gamma Variant                3  2020-08-07
28          54321093       Gamma Variant                3  2020-09-07

Conversion of Infected table into a DataFrame

In [ ]:
infected_df = infected_data
print(infected_df)

   medicare_card_num                type  infection_count        date
0           12345678            COVID-19                1  2021-01-01
1           12345678  SARS-Cov-2 Variant                2  2022-02-02
2           23456789            COVID-19                1  2020-03-03
3           23456789       Alpha Variant                1  2020-05-05
4           34567890            COVID-19                1  2021-04-04
5           34567890        Beta Variant                1  2021-06-06
6           45122911            COVID-19                2  2021-02-02
7           45122911       Gamma Variant                1  2020-07-07
8           56789012            COVID-19                1  2021-03-03
9           56789012       Delta Variant                2  2021-08-08
10          67890123            COVID-19                1  2020-04-04
11          67890123      Lambda Variant                1  2020-09-09
12          78901234            COVID-19                2  2022-02-02
13          78901234     Omicron Variant                1  2021-11-11
14          89012345            COVID-19                1  2020-01-01
15          89012345     Epsilon Variant                1  2020-10-10
16          90123456            COVID-19                2  2022-05-05
17          90123456  SARS-Cov-3 Variant                1  2021-12-12
18          01234567            COVID-19                1  2020-06-06
19          01234567        Beta Variant                1  2020-11-11
20          76543211            COVID-19                1  2021-01-01
21          65432112            COVID-19                1  2021-02-01
22          54321093            COVID-19                1  2021-03-01
23          76543211       Alpha Variant                2  2020-05-05
24          65432112       Alpha Variant                2  2020-06-05
25          54321093       Alpha Variant                2  2020-07-05
26          76543211       Gamma Variant                3  2020-07-07
27          65432112       Gamma Variant                3  2020-08-07
28          54321093       Gamma Variant                3  2020-09-07

In [ ]:
COMMAND = "SELECT * FROM Has_Received"
hasReceived_data = pd.read_sql_query(COMMAND, conn)
hasReceived_data

,medicare_card_num,vaccine_type,facility_name,web_address,date,dose_num
0,12345678,Pfizer,hospital1,hospital1.com,2022-01-10,1
1,23456789,AstraZeneca,hospital2,hospital2.com,2021-07-05,1
2,23456789,Johnson & Johnson,clinic1,clinic1.com,2022-02-01,2
3,34567890,Pfizer,hospital1,hospital1.com,2021-12-24,1
4,45122911,Bharat Biotech,clinic2,clinic2.com,2021-06-15,1
5,45122911,Novavax,special1,special1.com,2022-01-02,2
6,56789012,Covishield,hospital4,hospital4.com,2021-09-30,1
7,67890123,Sinopharm,clinic3,clinic3.com,2022-02-10,1
8,78901234,Pfizer,hospital2,hospital2.com,2021-07-02,1
9,78901234,Covishield,CLSC1,CLSC1.com,2022-01-15,2
10,90123456,Johnson & Johnson,clinic1,clinic1.com,2020-12-03,1
11,01234567,AstraZeneca,hospital2,hospital2.com,2022-01-08,1
12,12345670,Sinovac,hospital4,hospital4.com,2022-02-08,1
13,23456780,Pfizer,special1,special1.com,2021-10-11,1
14,34363499,AstraZeneca,special2,special2.com,2021-11-23,1
15,45678901,Johnson & Johnson,clinic2,clinic2.com,2021-12-05,1
16,56789111,Covovax,special2,special2.com,2022-01-09,1
17,98765432,Bharat Biotech,clinic2,clinic2.com,2021-09-20,1
18,87654321,Moderna,hospital1,hospital1.com,2021-12-01,1
19,87654321,AstraZeneca,hospital2,hospital2.com,2021-09-03,2
20,65432109,Sinopharm,clinic3,clinic3.com,2021-09-18,1
21,65432109,Covishield,CLSC1,CLSC1.com,2022-02-12,2

Conversion of Has_Received table into a DataFrame

In [ ]:
hasReceived_df = hasReceived_data
print(hasReceived_df)

   medicare_card_num       vaccine_type facility_name    web_address  \
0           12345678             Pfizer     hospital1  hospital1.com
1           23456789        AstraZeneca     hospital2  hospital2.com
2           23456789  Johnson & Johnson       clinic1    clinic1.com
3           34567890             Pfizer     hospital1  hospital1.com
4           45122911     Bharat Biotech       clinic2    clinic2.com
5           45122911            Novavax      special1   special1.com
6           56789012         Covishield     hospital4  hospital4.com
7           67890123          Sinopharm       clinic3    clinic3.com
8           78901234             Pfizer     hospital2  hospital2.com
9           78901234         Covishield         CLSC1      CLSC1.com
10          90123456  Johnson & Johnson       clinic1    clinic1.com
11          01234567        AstraZeneca     hospital2  hospital2.com
12          12345670            Sinovac     hospital4  hospital4.com
13          23456780             Pfizer      special1   special1.com
14          34363499        AstraZeneca      special2   special2.com
15          45678901  Johnson & Johnson       clinic2    clinic2.com
16          56789111            Covovax      special2   special2.com
17          98765432     Bharat Biotech       clinic2    clinic2.com
18          87654321            Moderna     hospital1  hospital1.com
19          87654321        AstraZeneca     hospital2  hospital2.com
20          65432109          Sinopharm       clinic3    clinic3.com
21          65432109         Covishield         CLSC1      CLSC1.com

          date  dose_num
0   2022-01-10         1
1   2021-07-05         1
2   2022-02-01         2
3   2021-12-24         1
4   2021-06-15         1
5   2022-01-02         2
6   2021-09-30         1
7   2022-02-10         1
8   2021-07-02         1
9   2022-01-15         2
10  2020-12-03         1
11  2022-01-08         1
12  2022-02-08         1
13  2021-10-11         1
14  2021-11-23         1
15  2021-12-05         1
16  2022-01-09         1
17  2021-09-20         1
18  2021-12-01         1
19  2021-09-03         2
20  2021-09-18         1
21  2022-02-12         2

In [ ]:
COMMAND = "SELECT * FROM Administers"
administers_data = pd.read_sql_query(COMMAND, conn)
administers_data

   facility_name    web_address       vaccine_type
0      hospital1  hospital1.com             Pfizer
1      hospital1  hospital1.com            Moderna
2      hospital2  hospital2.com        AstraZeneca
3        clinic1    clinic1.com  Johnson & Johnson
4       special1   special1.com            Novavax
5          CLSC1      CLSC1.com            Sinovac
6      hospital3  hospital3.com          Sinopharm
7        clinic2    clinic2.com     Bharat Biotech
8       special2   special2.com            Covovax
9      hospital4  hospital4.com         Covishield
10     hospital1  hospital1.com        AstraZeneca
11     hospital2  hospital2.com             Pfizer
12       clinic1    clinic1.com            Moderna
13      special1   special1.com             Pfizer
14         CLSC1      CLSC1.com         Covishield
15     hospital3  hospital3.com            Covovax
16       clinic2    clinic2.com  Johnson & Johnson
17      special2   special2.com        AstraZeneca
18     hospital4  hospital4.com            Sinovac
19       clinic3    clinic3.com          Sinopharm

Conversion of Administers table into a DataFrame

In [ ]:
administers_df = administers_data
print(administers_df)

   facility_name    web_address       vaccine_type
0      hospital1  hospital1.com             Pfizer
1      hospital1  hospital1.com            Moderna
2      hospital2  hospital2.com        AstraZeneca
3        clinic1    clinic1.com  Johnson & Johnson
4       special1   special1.com            Novavax
5          CLSC1      CLSC1.com            Sinovac
6      hospital3  hospital3.com          Sinopharm
7        clinic2    clinic2.com     Bharat Biotech
8       special2   special2.com            Covovax
9      hospital4  hospital4.com         Covishield
10     hospital1  hospital1.com        AstraZeneca
11     hospital2  hospital2.com             Pfizer
12       clinic1    clinic1.com            Moderna
13      special1   special1.com             Pfizer
14         CLSC1      CLSC1.com         Covishield
15     hospital3  hospital3.com            Covovax
16       clinic2    clinic2.com  Johnson & Johnson
17      special2   special2.com        AstraZeneca
18     hospital4  hospital4.com            Sinovac
19       clinic3    clinic3.com          Sinopharm

In [ ]:
COMMAND = "SELECT * FROM Managed"
managed_data = pd.read_sql_query(COMMAND, conn)
managed_data

,facility_name,web_address,medicare_card_num,start_date,end_date
0,hospital1,hospital1.com,12345678,2022-01-01,2022-01-31
1,hospital2,hospital2.com,34567890,2022-02-01,2022-02-28
2,clinic1,clinic1.com,56789012,2022-03-01,2022-03-31
3,special1,special1.com,78901234,2022-04-01,2022-04-30
4,CLSC1,CLSC1.com,90123456,2022-05-01,2022-05-31
5,hospital3,hospital3.com,12345678,2022-06-01,None
6,clinic2,clinic2.com,34567890,2022-07-01,None
7,special2,special2.com,56789012,2022-08-01,None
8,hospital4,hospital4.com,78901234,2022-09-01,None
9,clinic3,clinic3.com,90123456,2022-10-01,2022-10-31
10,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,10987654,2022-07-01,None

Conversion of Managed table into a DataFrame

In [ ]:
managed_df = managed_data
print(managed_df)

                    facility_name                        web_address  \
0                       hospital1                      hospital1.com
1                       hospital2                      hospital2.com
2                         clinic1                        clinic1.com
3                        special1                       special1.com
4                           CLSC1                          CLSC1.com
5                       hospital3                      hospital3.com
6                         clinic2                        clinic2.com
7                        special2                       special2.com
8                       hospital4                      hospital4.com
9                         clinic3                        clinic3.com
10  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com

   medicare_card_num  start_date    end_date
0           12345678  2022-01-01  2022-01-31
1           34567890  2022-02-01  2022-02-28
2           56789012  2022-03-01  2022-03-31
3           78901234  2022-04-01  2022-04-30
4           90123456  2022-05-01  2022-05-31
5           12345678  2022-06-01        None
6           34567890  2022-07-01        None
7           56789012  2022-08-01        None
8           78901234  2022-09-01        None
9           90123456  2022-10-01  2022-10-31
10          10987654  2022-07-01        None

In [ ]:
COMMAND = "SELECT * FROM Worked"
worked_data = pd.read_sql_query(COMMAND, conn)
worked_data

,facility_name,web_address,medicare_card_num,start_date,end_date,role
0,hospital1,hospital1.com,12345678,2022-01-01,2022-01-31,Manager
1,hospital1,hospital1.com,23456789,2022-01-01,None,Doctor
2,hospital2,hospital2.com,34567890,2022-02-01,2022-02-28,Manager
3,hospital2,hospital2.com,45122911,2022-02-01,None,Doctor
4,clinic1,clinic1.com,56789012,2022-03-01,2022-03-31,Manager
5,clinic1,clinic1.com,67890123,2022-03-01,None,Doctor
6,special1,special1.com,78901234,2022-04-01,2022-04-30,Manager
7,special1,special1.com,89012345,2022-04-01,None,Doctor
8,CLSC1,CLSC1.com,90123456,2022-05-01,2022-05-31,Manager
9,CLSC1,CLSC1.com,01234567,2022-05-01,2022-05-31,Doctor
10,hospital3,hospital3.com,12345678,2022-06-01,None,Manager
11,hospital3,hospital3.com,23456789,2022-06-01,2022-06-30,Doctor
12,clinic2,clinic2.com,34567890,2022-07-01,None,Manager
13,clinic2,clinic2.com,45122911,2022-07-01,2022-07-31,Doctor
14,special2,special2.com,56789012,2022-08-01,None,Manager
15,special2,special2.com,67890123,2022-08-01,None,Doctor
16,hospital4,hospital4.com,78901234,2022-09-01,None,Manager
17,hospital4,hospital4.com,89012345,2022-09-01,None,Doctor
18,clinic3,clinic3.com,90123456,2022-10-01,2022-10-31,Manager
19,clinic3,clinic3.com,01234567,2020-10-01,2020-10-30,Doctor
20,hospital4,hospital4.com,90123456,2021-10-01,2021-10-30,Doctor
21,special2,special2.com,45122911,2022-10-01,None,Doctor
22,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,76543211,2022-07-01,None,Doctor
23,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,65432112,2022-07-01,None,Nurse
24,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,54321093,2022-07-01,None,Nurse
25,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,43210987,2022-07-01,2022-07-31,Doctor
26,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,32109876,2022-07-01,None,Nurse
27,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,21098765,2022-07-01,2022-07-31,Nurse
28,Hospital Maisonneuve Rosemont,Hospital-Maisonneuve-Rosemont.com,10987654,2022-07-01,None,Manager

Conversion of Worked table into a DataFrame

In [ ]:
worked_df = worked_data
print(worked_df)

                    facility_name                        web_address  \
0                       hospital1                      hospital1.com
1                       hospital1                      hospital1.com
2                       hospital2                      hospital2.com
3                       hospital2                      hospital2.com
4                         clinic1                        clinic1.com
5                         clinic1                        clinic1.com
6                        special1                       special1.com
7                        special1                       special1.com
8                           CLSC1                          CLSC1.com
9                           CLSC1                          CLSC1.com
10                      hospital3                      hospital3.com
11                      hospital3                      hospital3.com
12                        clinic2                        clinic2.com
13                        clinic2                        clinic2.com
14                       special2                       special2.com
15                       special2                       special2.com
16                      hospital4                      hospital4.com
17                      hospital4                      hospital4.com
18                        clinic3                        clinic3.com
19                        clinic3                        clinic3.com
20                      hospital4                      hospital4.com
21                       special2                       special2.com
22  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com
23  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com
24  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com
25  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com
26  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com
27  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com
28  Hospital Maisonneuve Rosemont  Hospital-Maisonneuve-Rosemont.com

   medicare_card_num  start_date    end_date     role
0           12345678  2022-01-01  2022-01-31  Manager
1           23456789  2022-01-01        None   Doctor
2           34567890  2022-02-01  2022-02-28  Manager
3           45122911  2022-02-01        None   Doctor
4           56789012  2022-03-01  2022-03-31  Manager
5           67890123  2022-03-01        None   Doctor
6           78901234  2022-04-01  2022-04-30  Manager
7           89012345  2022-04-01        None   Doctor
8           90123456  2022-05-01  2022-05-31  Manager
9           01234567  2022-05-01  2022-05-31   Doctor
10          12345678  2022-06-01        None  Manager
11          23456789  2022-06-01  2022-06-30   Doctor
12          34567890  2022-07-01        None  Manager
13          45122911  2022-07-01  2022-07-31   Doctor
14          56789012  2022-08-01        None  Manager
15          67890123  2022-08-01        None   Doctor
16          78901234  2022-09-01        None  Manager
17          89012345  2022-09-01        None   Doctor
18          90123456  2022-10-01  2022-10-31  Manager
19          01234567  2020-10-01  2020-10-30   Doctor
20          90123456  2021-10-01  2021-10-30   Doctor
21          45122911  2022-10-01        None   Doctor
22          76543211  2022-07-01        None   Doctor
23          65432112  2022-07-01        None    Nurse
24          54321093  2022-07-01        None    Nurse
25          43210987  2022-07-01  2022-07-31   Doctor
26          32109876  2022-07-01        None    Nurse
27          21098765  2022-07-01  2022-07-31    Nurse
28          10987654  2022-07-01        None  Manager

Test to query database

In [ ]:
print(worked_df['end_date'])

0     2022-01-31
1           None
2     2022-02-28
3           None
4     2022-03-31
5           None
6     2022-04-30
7           None
8     2022-05-31
9     2022-05-31
10          None
11    2022-06-30
12          None
13    2022-07-31
14          None
15          None
16          None
17          None
18    2022-10-31
19    2020-10-30
20    2021-10-30
21          None
22          None
23          None
24          None
25    2022-07-31
26          None
27    2022-07-31
28          None
Name: end_date, dtype: object

Task 3 - Question 1

Save DataFrames into .csv files

In [ ]:
employees_df.to_csv('employees.csv', index=False)
facilities_df.to_csv('facilities.csv', index=False)
infections_df.to_csv('infections.csv', index=False)
vaccines_df.to_csv('vaccines.csv', index=False)
infected_df.to_csv('infected.csv', index=False)
hasReceived_df.to_csv('hasReceived.csv', index=False)
administers_df.to_csv('administers.csv', index=False)
managed_df.to_csv('managed.csv', index=False)
worked_df.to_csv('worked.csv', index=False)

Task 3 - Question 2

Write the queries to extract data fron DataFrame directly

Query 1: Query that retrieves a list of all employees, along with the details of their vaccinations if they have been vaccinated. If an employee hasn't been vaccinated, the ‘vaccine_name’ and ‘facility_name’ fields will be NULL for that employee (outer-join)

In [ ]:
# Merging employees and hasReceived on medicare_card_num
merged_df = employees_df.merge(hasReceived_df, on='medicare_card_num', how='left')

# Merging the result with facilities_df on web_address and name (renaming it to facility_name)
final_df = merged_df.merge(facilities_df, left_on=['facility_name', 'web_address'], right_on=['name', 'web_address'], how='left')

print(final_df[['medicare_card_num', 'first_name', 'last_name', 'vaccine_type', 'facility_name']])

   medicare_card_num first_name  last_name       vaccine_type facility_name
0           12345678      Alice    Roberts             Pfizer     hospital1
1           23456789        Bob    Johnson        AstraZeneca     hospital2
2           23456789        Bob    Johnson  Johnson & Johnson       clinic1
3           34567890      Carol   Williams             Pfizer     hospital1
4           45122911       Dave      Jones     Bharat Biotech       clinic2
5           45122911       Dave      Jones            Novavax      special1
6           56789012        Eve      Brown         Covishield     hospital4
7           67890123      Frank      Smith          Sinopharm       clinic3
8           78901234      Grace     Taylor             Pfizer     hospital2
9           78901234      Grace     Taylor         Covishield         CLSC1
10          89012345      Harry      Adams                NaN           NaN
11          90123456        Ivy     Martin  Johnson & Johnson       clinic1
12          01234567       Jack        Lee        AstraZeneca     hospital2
13          12345670      Kathy       King            Sinovac     hospital4
14          23456780      Larry      Baker             Pfizer      special1
15          34363499       Mona     Turner        AstraZeneca      special2
16          45678901       Nate       Hill  Johnson & Johnson       clinic2
17          56789111     Olivia      James            Covovax      special2
18          98765432      Peter      Clark     Bharat Biotech       clinic2
19          87654321      Queen      Scott            Moderna     hospital1
20          87654321      Queen      Scott        AstraZeneca     hospital2
21          76543210        Ron    Stewart                NaN           NaN
22          65432109      Sarah       Hall          Sinopharm       clinic3
23          65432109      Sarah       Hall         Covishield         CLSC1
24          54321098        Tom      Perez                NaN           NaN
25          76543211     Ursula     Nelson                NaN           NaN
26          65432112        Vic   Phillips                NaN           NaN
27          54321093      Wanda  Rodriguez                NaN           NaN
28          43210987     Xander     Harris                NaN           NaN
29          32109876       John        Doe                NaN           NaN
30          21098765       Momo      Diane                NaN           NaN
31          10987654     Philip      Tomas                NaN           NaN

Query 2: Give the number of missing values of the attribute ‘end_date’ in the table ‘Worked’

In [ ]:
missing_values_count = worked_df['end_date'].isnull().sum()

In [ ]:
print(f"Number of missing values in 'end_date' attribute: {missing_values_count}")

Number of missing values in 'end_date' attribute: 16

Query 3: Give the first and last names of Employees that are actively working (eg. Has no end_date)

In [ ]:
# rows in worked_df where end_date is null
active_work_periods = worked_df[worked_df['end_date'].isnull()]

# inner join of worked_df with employee_df
active_employees = active_work_periods.merge(employees_df[['medicare_card_num', 'first_name', 'last_name']],
                                            on='medicare_card_num',
                                            how='inner')

# of active employees print the first_name and last_name columns
print(active_employees[['first_name', 'last_name']])

   first_name  last_name
0         Bob    Johnson
1        Dave      Jones
2        Dave      Jones
3       Frank      Smith
4       Frank      Smith
5       Harry      Adams
6       Harry      Adams
7       Alice    Roberts
8       Carol   Williams
9         Eve      Brown
10      Grace     Taylor
11     Ursula     Nelson
12        Vic   Phillips
13      Wanda  Rodriguez
14       John        Doe
15     Philip      Tomas

Query 4: Give the first and last names of Employees that have worked in only one facility

In [ ]:
# Group by medicare_card_num and count the unique facility_ids for each employee
employee_facility_count = worked_df.groupby('medicare_card_num')['facility_name'].nunique()

# Filter employees who have worked in only one facility
single_facility_employees = employee_facility_count[employee_facility_count == 1].index.tolist()

# Extract and print the first_name and last_name of these employees from employees_df
result = employees_df[employees_df['medicare_card_num'].isin(single_facility_employees)][['first_name', 'last_name']]
print(result)

   first_name  last_name
20     Ursula     Nelson
21        Vic   Phillips
22      Wanda  Rodriguez
23     Xander     Harris
24       John        Doe
25       Momo      Diane
26     Philip      Tomas

Query 5: Query that categorizes the records based on the ‘role’ and display the number of employees that occupy each role

In [ ]:
# Group by role and count the distinct num of employees for each role

number_of_employees_per_role = worked_df.groupby('role')['medicare_card_num'].nunique()
print(number_of_employees_per_role)

role
Doctor     8
Manager    6
Nurse      4
Name: medicare_card_num, dtype: int64

Query 6: Query that display the facilities with the minimum and maximum capacity values (eg. the minimum & maximum values capacity the facilities have are respectively 5 and 10)

In [ ]:
min_capacity = facilities_df['capacity'].min()
max_capacity = facilities_df['capacity'].max()

result_df = facilities_df[(facilities_df['capacity'] == min_capacity) |
                          (facilities_df['capacity'] == max_capacity)][['name', 'capacity']]

print(result_df)

       name  capacity
2   clinic1         5
3  special1         5
4     CLSC1        10

Query 7: Query that matches the employees that have receive their vaccines from the same facility (self-join)

In [ ]:

# Perform a self-join on the facility_name column
merged_df = hasReceived_df.merge(hasReceived_df, on='facility_name', suffixes=('_1', '_2'))

# Filter to ensure no redundant pairs and no self-matching rows
result_df = merged_df[merged_df['medicare_card_num_1'] < merged_df['medicare_card_num_2']]

# Display the results
print(result_df[['medicare_card_num_1', 'medicare_card_num_2', 'facility_name']])

   medicare_card_num_1 medicare_card_num_2 facility_name
1             12345678            34567890     hospital1
2             12345678            87654321     hospital1
5             34567890            87654321     hospital1
10            23456789            78901234     hospital2
12            23456789            87654321     hospital2
16            78901234            87654321     hospital2
17            01234567            23456789     hospital2
18            01234567            78901234     hospital2
20            01234567            87654321     hospital2
26            23456789            90123456       clinic1
30            45122911            45678901       clinic2
31            45122911            98765432       clinic2
34            45678901            98765432       clinic2
40            23456780            45122911      special1
44            12345670            56789012     hospital4
48            65432109            67890123       clinic3
52            65432109            78901234         CLSC1
55            34363499            56789111      special2